all:
	g++  -std=c++11 -O3 main.cpp Server.cpp VerticesSubQualitiesManager.cpp result_management.cpp PostProcessingManagement.cpp RelativeBasedMeasure.cpp pruning_management.cpp PrefBasedSorter.cpp pattern.cpp pattern_sampler.cpp pattern_extractor.cpp HashtagSubQualitiesManager.cpp covering_management.cpp graph_loader.cpp graph.cpp jacobi.cpp string_management.cpp utils.cpp -o EventDetectionServer -lpthread

